version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/base"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/images/devops"
    schedule:
      interval: "weekly"
